[book]
authors = ["dondarubin"]
language = "en"
src = "src"
title = "StartON Launchpad — Web3 платформа для запуска токенов"

[build]
build-dir = "book"
create-missing = true

[preprocessor.drawio]
command = "mdbook-drawio"

[output.html]
additional-css = ["src/_assets/custom.css"]
additional-js = []
